import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
const result=await build({entryPoints:['SimCity/app.mjs'],bundle:true,minify:true,format:'iife',write:false,target:['safari16','chrome110']});
let page=await readFile('SimCity/template.html.in','utf8');
const css=await readFile('SimCity/style.css','utf8');
page=page.replace('/*STYLE*/',()=>css).replace('/*BUNDLED_GAME*/',()=>result.outputFiles[0].text);
const music=await readFile('Audio/Yorktown-Starlit-Resolve-Warm-Cello.mp3');
if(music.length<100000||music.length>8000000)throw new Error('Approved cello soundtrack is missing or outside the expected size.');
page=page.replace('__YORKTOWN_APPROVED_CELLO__',()=>`data:audio/mpeg;base64,${music.toString('base64')}`);
if(page.includes('__YORKTOWN_')||(page.match(/data:audio\/mpeg;base64,/g)||[]).length!==1)throw new Error('Exactly one approved soundtrack must be embedded.');
const license=await readFile('THIRD-PARTY-LICENSES.txt','utf8');
page=page.replace('</body>',()=>`<!-- Third-party license\n${license}\n-->\n</body>`);
if(page.includes('/*STYLE*/')||page.includes('/*BUNDLED_GAME*/'))throw new Error('Build is incomplete: unresolved template placeholders.');
await writeFile('simcity.html',page);
await writeFile('index.html',page);
await writeFile('showcase.html',page);
await writeFile('SimCity/template.html',page);
await writeFile('Yorktown-Continuum-City-v11.0.0.html',page);
console.log(`Built index.html and simcity.html (${Math.round(Buffer.byteLength(page)/1024)} KiB each), fully offline.`);
