import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
const worker=await build({entryPoints:['SimCity/simulation-worker.mjs'],bundle:true,minify:true,format:'iife',write:false,target:['safari16','chrome110']});
const result=await build({entryPoints:['SimCity/app.mjs'],bundle:true,minify:true,format:'iife',write:false,target:['safari16','chrome110'],plugins:[{name:'simulation-worker',setup(b){b.onResolve({filter:/^yorktown-worker-source$/},()=>({path:'worker',namespace:'worker-source'}));b.onLoad({filter:/.*/,namespace:'worker-source'},()=>({contents:`export const SIMULATION_WORKER_SOURCE=${JSON.stringify(worker.outputFiles[0].text)};`,loader:'js'}));}}]});
let page=await readFile('SimCity/template.html.in','utf8');
const css=await readFile('SimCity/style.css','utf8');
page=page.replace('/*STYLE*/',()=>css).replace('/*BUNDLED_GAME*/',()=>result.outputFiles[0].text);
const music=await readFile('Audio/Firstlight.mp3');
if(music.length<100000||music.length>8000000)throw new Error('Approved Firstlight soundtrack is missing or outside the expected size.');
if((page.match(/__YORKTOWN_APPROVED_MUSIC__/g)||[]).length!==1)throw new Error('Exactly one approved soundtrack source must be present.');
const license=await readFile('THIRD-PARTY-LICENSES.txt','utf8');
page=page.replace('</body>',()=>`<!-- Third-party license\n${license}\n-->\n</body>`);
if(page.includes('/*STYLE*/')||page.includes('/*BUNDLED_GAME*/'))throw new Error('Build is incomplete: unresolved template placeholders.');
const webPage=page.replace('__YORKTOWN_APPROVED_MUSIC__','Audio/Firstlight.mp3');
const nestedPage=page.replace('__YORKTOWN_APPROVED_MUSIC__','../Audio/Firstlight.mp3');
const offlinePage=page.replace('__YORKTOWN_APPROVED_MUSIC__',()=>`data:audio/mpeg;base64,${music.toString('base64')}`);
if([webPage,nestedPage,offlinePage].some(p=>p.includes('__YORKTOWN_')))throw new Error('Soundtrack build is incomplete.');
await writeFile('simcity.html',webPage);
await writeFile('index.html',webPage);
await writeFile('showcase.html',webPage);
await writeFile('SimCity/template.html',nestedPage);
await writeFile('Yorktown-Branch-Evolution-v11.2.0.html',offlinePage);
console.log(`Built web entries (${Math.round(Buffer.byteLength(webPage)/1024)} KiB) with deferred audio streaming and a fully offline single file (${Math.round(Buffer.byteLength(offlinePage)/1024)} KiB).`);
