import {build} from 'esbuild';
import {readFile,writeFile} from 'node:fs/promises';
const result=await build({entryPoints:['SimCity/app.mjs'],bundle:true,minify:true,format:'iife',write:false,target:['safari16','chrome110']});
let page=await readFile('SimCity/template.html.in','utf8');
const css=await readFile('SimCity/style.css','utf8');
page=page.replace('/*STYLE*/',()=>css).replace('/*BUNDLED_GAME*/',()=>result.outputFiles[0].text);
const music=await readFile('Audio/Yorktown-Starlit-Resolve-Warm-Cello.mp3');
if(music.length<100000||music.length>8000000)throw new Error('Approved cello soundtrack is missing or outside the expected size.');
if((page.match(/__YORKTOWN_APPROVED_CELLO__/g)||[]).length!==1)throw new Error('Exactly one approved soundtrack source must be present.');
const license=await readFile('THIRD-PARTY-LICENSES.txt','utf8');
page=page.replace('</body>',()=>`<!-- Third-party license\n${license}\n-->\n</body>`);
if(page.includes('/*STYLE*/')||page.includes('/*BUNDLED_GAME*/'))throw new Error('Build is incomplete: unresolved template placeholders.');
const webPage=page.replace('__YORKTOWN_APPROVED_CELLO__','Audio/Yorktown-Starlit-Resolve-Warm-Cello.mp3');
const nestedPage=page.replace('__YORKTOWN_APPROVED_CELLO__','../Audio/Yorktown-Starlit-Resolve-Warm-Cello.mp3');
const offlinePage=page.replace('__YORKTOWN_APPROVED_CELLO__',()=>`data:audio/mpeg;base64,${music.toString('base64')}`);
if([webPage,nestedPage,offlinePage].some(p=>p.includes('__YORKTOWN_')))throw new Error('Soundtrack build is incomplete.');
await writeFile('simcity.html',webPage);
await writeFile('index.html',webPage);
await writeFile('showcase.html',webPage);
await writeFile('SimCity/template.html',nestedPage);
await writeFile('Yorktown-Continuum-City-v11.0.0.html',offlinePage);
console.log(`Built web entries (${Math.round(Buffer.byteLength(webPage)/1024)} KiB) with deferred audio streaming and a fully offline single file (${Math.round(Buffer.byteLength(offlinePage)/1024)} KiB).`);
