import {TYPES,idx,xy,wrapX} from './catalog.mjs';
import {PLAN_TIERS,planExpansion,commitExpansion,areaBounds} from './assisted-planning.mjs';
import {previewLine,constructLine,lineAt,lineMaintenance} from './continuum.mjs';
import {analyze,forecast,build,buildingReport} from './engine.mjs';
const $=id=>document.getElementById(id),money=v=>Math.round(v).toLocaleString('en-US');
export class ContinuumUI{
 constructor(h){this.h=h;this.selection=null;$('assistant-button').onclick=()=>this.start();$('new-architecture').onclick=()=>this.tour();}
 start(){this.h.close();this.h.view.showPlan(null);this.h.choose('assist');this.h.view.setMode('build');this.h.notice('拖曳框選 6 × 6 至 32 × 24 格。系統會保留既有建築，並先估算供應、需求與費用。');}
 selected(ids,tool){if(tool==='assist'){this.assist(ids);return true;}if(tool==='line'){this.line(ids);return true;}return false;}
 assist(ids,chosen='balanced'){
  const s=this.h.city(),a=this.h.analysis(),f=forecast(s,a),bounds=areaBounds(ids);this.selection=ids;const plans=PLAN_TIERS.map(t=>planExpansion(s,a,f,ids,t.id,analyze,forecast));let n=PLAN_TIERS.findIndex(t=>t.id===chosen);if(!plans[n].ok)n=plans.findIndex(p=>p.ok);const p=plans[n];
  this.h.show('延續街區 · 選區與投資','assistant',`<p class="modal-intro">已框選 ${bounds?.w||0} × ${bounds?.h||0} 格。延伸附近市區的分區密度；保留既有建築，先完成道路、供應與公共服務。</p><div class="plan-tiers">${PLAN_TIERS.map((t,j)=>`<button data-plan-tier="${t.id}" class="${j===n?'active':''}" ${!plans[j].ok?'disabled':''}><strong>${t.name}</strong><small>${plans[j].ok?money(plans[j].cost)+' · '+plans[j].sites+' 格分區':plans[j].error}</small></button>`).join('')}</div>${p?`<div class="plan-quote"><canvas id="planning-map" width="720" height="340" aria-label="施工規劃：灰色道路、綠色住宅、藍色商業、金色工業及公共設施"></canvas><div class="plan-key"><span>灰 · 道路</span><span>綠 · 住宅 / 公園</span><span>藍 · 商業</span><span>金 · 工業 / 水電</span></div><p>${p.pattern} · 住宅 ${p.zoneCounts.R} / 商業 ${p.zoneCounts.C} / 工業 ${p.zoneCounts.I}</p><div class="stat-cards"><div class="stat-card"><small>施工費</small><strong>${money(p.cost)}</strong></div><div class="stat-card"><small>新增月支出</small><strong>${money(p.monthlyExtra)}</strong></div><div class="stat-card"><small>施工後財庫</small><strong>${money(p.remaining)}</strong></div></div><p class="tiny">第四階容量的最低水電／氧氣／散熱覆蓋 ${Math.round(p.coverage*100)}%。預留 ${money(p.reserve)} 營運資金；這不是第八階的無限容量保證。未使用的預算保留在財庫。長出建築前的月收支 ${money(p.net)}。</p></div><div class="modal-actions"><button id="plan-commit" class="primary">確認施工 · ${money(p.cost)}</button><button id="plan-reselect">重新框選</button></div>`:`<p class="notice">${plans[1].error}</p><button id="plan-reselect" class="primary">重新框選</button>`}`);
  for(const b of document.querySelectorAll('[data-plan-tier]'))b.onclick=()=>this.assist(ids,b.dataset.planTier);
  $('plan-reselect').onclick=()=>this.start();if(!p)return;this.h.view.showPlan(p);this.drawPlan(p,s);$('plan-commit').onclick=()=>{const result=commitExpansion(this.h.city(),p,build);if(result.ok){this.h.view.showPlan(null);this.h.close();this.h.choose('inspect');this.h.done(result);this.h.notice(`街區已完成基礎建設：${p.sites} 格分區從空地自然成長，支出 ${money(result.cost)}。按 1× 推進城市。`);}else this.h.notice(result.error,true);};
 }
 drawPlan(p,s){const canvas=$('planning-map'),c=canvas.getContext('2d'),b=p.bounds,k=Math.min(680/b.w,300/b.h),ox=(720-b.w*k)/2,oy=(340-b.h*k)/2,changes=new Map(p.changes.map(c=>[c.i,c]));c.fillStyle='#e2e7dc';c.fillRect(0,0,720,340);for(let y=0;y<b.h;y++)for(let x=0;x<b.w;x++){const i=idx(wrapX(b.x+x),b.y+y),planned=changes.get(i);c.fillStyle=planned?(TYPES[planned.type].group==='utility'?'#d5aa5e':planned.type==='road'?'#526d76':planned.type==='park'?'#8fa97b':planned.type.toUpperCase()==='R'?'#72b59b':planned.type.toUpperCase()==='C'?'#6a9dbb':planned.type.toUpperCase()==='I'?'#cca267':'#bbbcaa'):s.cells[i].type?'#aeb2a8':'#d4dcd2';c.fillRect(ox+x*k+1,oy+y*k+1,k-2,k-2);if(s.cells[i].type&&!planned){c.fillStyle='#6e7b78';c.fillRect(ox+x*k+k*.35,oy+y*k+k*.35,k*.3,k*.3);}}}
 line(ids,extend=null){const s=this.h.city(),p=previewLine(s,ids,{extend});this.h.show(extend===null?'天際長廊 · 自訂長度':'天際長廊 · 延長一段','line-plan',p.ok?`<p class="modal-intro">側面採背景迷彩，帶冷青色差；兩端保留入口與可見的六層公共街道。可以步行、搭中央列車或公共升降梯。</p><div class="stat-cards"><div class="stat-card"><small>長 / 寬 / 高</small><strong>${p.segments*40} / 80 / 120 m</strong></div><div class="stat-card"><small>施工費</small><strong>${money(p.cost)}</strong></div><div class="stat-card"><small>月維護</small><strong>${40+p.segments*55}</strong></div></div><p class="notice">${p.segments*180} 住宅容量、${p.segments*40} 工作容量；外部道路、水電、氧氣與散熱仍需供應。太陽能與循環設備只能補足部分消耗。${p.warning}</p><div class="modal-actions"><button id="line-commit" class="primary" ${s.cash<p.cost?'disabled':''}>${p.extension?'延長':'建造'} · ${money(p.cost)}</button><button id="line-reselect">重新選擇</button></div>`:`<p class="notice">${p.error}</p><button id="line-reselect" class="primary">返回建造</button>`);
  $('line-reselect').onclick=()=>{this.h.close();this.h.choose('line');};if(p.ok){const ghost={changes:p.fresh.map(i=>({i,type:'line'}))};this.h.view.showPlan(ghost);$('line-commit').onclick=()=>{const r=constructLine(this.h.city(),previewLine(this.h.city(),ids,{extend}));if(r.ok){this.h.view.showPlan(null);this.h.close();this.h.choose('inspect');this.h.done(r);this.h.view.focus(p.anchor);this.h.notice(p.warning||'天際長廊已建成。選取後進入公共街道，或在資訊中逐段延長。');}else this.h.notice(r.error,true);};}
 }
 building(i){const s=this.h.city(),l=lineAt(s,i);if(!l)return false;const a=this.h.analysis(),r=buildingReport(s,a,l.anchor),c=s.cells[l.anchor];this.h.show('天際長廊 · 城市中的城市','line-building',`<p class="modal-intro">${l.segments*40}m × 80m × 120m · 六層公共街道。中央列車連接兩端；有道路接在兩端時，內部運輸也參與城市通勤。</p><div class="stat-cards"><div class="stat-card"><small>居民 / 容量</small><strong>${money(r.pop)} / ${money(r.capacity)}</strong></div><div class="stat-card"><small>工作 / 使用</small><strong>${money(r.jobs)} / ${money(r.filled)}</strong></div><div class="stat-card"><small>月維護</small><strong>${money(r.upkeep)}</strong></div></div><p class="notice">供電 ${Math.round(a.power.coverage[l.anchor]*100)}% · 水 ${Math.round(a.water.coverage[l.anchor]*100)}% · 氧氣 ${Math.round(a.space.oxygen[l.anchor]*100)}% · 散熱 ${Math.round(a.space.cooling[l.anchor]*100)}%。較高階分區發展仍需要更多外部基礎設施。</p><div class="modal-actions"><button id="line-enter" class="primary">進入公共街道</button><button id="line-extend" ${l.segments>=16?'disabled':''}>延長 40m · 6,000</button><button id="line-locate">看兩端與迷彩</button></div><p class="tiny">拆除任一地基會選取整座長廊，避免留下失去入口的半棟建築。供應不足時，列車與升降梯暫停。</p>`);$('line-enter').onclick=()=>{this.h.close();this.h.view.enterInterior(l.anchor);};$('line-extend').onclick=()=>this.line([],l.anchor);$('line-locate').onclick=()=>{this.h.close();this.h.view.focus(l.anchor);};return true;}
 tour(){const s=this.h.city(),types=['sail','shell','line'];this.h.show('晨光新街區','new-architecture',`<p class="modal-intro">這些已是主遊戲的建築，會計入人口、供應與維護。先前存檔不會被自動拆改；若未興建，可從地標建造。</p><div class="plan-tiers">${types.map(type=>{const i=s.cells.findIndex((c,i)=>c.type===type&&!c.subplot&&(!c.plot||c.plot===i));return `<button data-tour-type="${type}"><strong>${TYPES[type].name}</strong><small>${i>=0?'前往已建成的街區':'選擇建造 · '+money(TYPES[type].cost)}</small></button>`;}).join('')}</div>`);document.querySelectorAll('[data-tour-type]').forEach(b=>b.onclick=()=>{const t=b.dataset.tourType,i=s.cells.findIndex((c,i)=>c.type===t&&!c.subplot&&(!c.plot||c.plot===i));this.h.close();if(i>=0){this.h.view.focus(i);this.h.select(i);}else{this.h.choose(t);document.body.classList.add('tools-open');}});}
}
