import * as T from '../YorktownPreview/three.module.js';
function merged(parts){const flat=parts.map(g=>g.index?g.toNonIndexed():g),out=new T.BufferGeometry();for(const [n,size]of [['position',3],['normal',3],['uv',2]]){const a=new Float32Array(flat.reduce((v,g)=>v+g.attributes[n].array.length,0));let at=0;for(const g of flat){a.set(g.attributes[n].array,at);at+=g.attributes[n].array.length;}out.setAttribute(n,new T.BufferAttribute(a,size));}for(const g of new Set([...flat,...parts]))g.dispose();return out;}
function ribs(low=false,far=false){const p=[],n=far?3:low?5:14;for(let j=0;j<n;j++){const z=-.45+j*.90/(n-1),g=new T.TorusGeometry(.38*(1-.38*Math.abs(z)),low?.013:.008,far?3:4,far?8:low?10:24);g.translate(0,0,z);p.push(g);}for(const a of [0,Math.PI/2,Math.PI,Math.PI*1.5]){const g=new T.CylinderGeometry(.005,.005,.92,4);g.rotateX(Math.PI/2);g.translate(Math.cos(a)*.32,Math.sin(a)*.32,0);p.push(g);}return merged(p);}
function yard(low=false){
 const parts=[],box=(x,y,z,w,h,d)=>{const g=new T.BoxGeometry(w,h,d);g.translate(x,y,z);parts.push(g);};
 for(const x of [-.45,.45])for(const z of [-.44,.44])box(x,0,z,.047,1,.047);
 for(const x of [-.45,.45])box(x,.46,0,.04,.08,.92);
 for(const z of [-.44,.44])box(0,.46,z,.92,.08,.04);
 if(!low)for(const x of [-.45,.45])for(let k=0;k<5;k++){
  const z=-.44+k*.176,a=new T.Vector3(x,.30,z),b=new T.Vector3(x,.46,z+.176);
  parts.push(new T.TubeGeometry(new T.LineCurve3(a,b),1,.009,4));
  box(x,.28,z+.088,.018,.025,.176);
 }
 return merged(parts);
}
function press(low=false){const p=[];for(const x of [-.32,.32])for(const z of [-.30,.30]){const g=new T.CylinderGeometry(.038,.038,.88,low?4:12);g.translate(x,0,z);p.push(g);}for(const y of [-.43,.43]){const g=new T.BoxGeometry(.91,.14,.91);g.translate(0,y,0);p.push(g);}const mold=new T.BoxGeometry(.51,.42,.58);p.push(mold);return merged(p);}
function roof(low=false){const p=[];for(let j=0;j<5;j++){const s=new T.Shape();s.moveTo(-.5,-.15);s.lineTo(.5,.32);s.lineTo(.5,.21);s.lineTo(-.5,-.24);s.closePath();const g=new T.ExtrudeGeometry(s,{depth:.17,steps:1,bevelEnabled:!low,bevelSize:.007,bevelThickness:.007,bevelSegments:1});g.rotateY(Math.PI/2);g.translate(-.42+j*.20,0,0);p.push(g);}return merged(p).translate(-.07,0,0);}
function hullPanels(){const p=[];for(const side of [-1,1]){for(const r of [.15,.27,.38,.46]){const g=new T.TorusGeometry(r,.0019,4,40).rotateX(Math.PI/2);g.translate(0,side*(Math.sqrt(.25-r*r)+.003),0);p.push(g);}for(let k=0;k<8;k++){const a=k*Math.PI/4,points=Array.from({length:17},(_,j)=>{const u=.06+j*.43/16;return new T.Vector3(Math.cos(a)*u,side*(Math.sqrt(.25-u*u)+.005),Math.sin(a)*u);});p.push(new T.TubeGeometry(new T.CatmullRomCurve3(points),16,.0014,4));}}return merged(p);}
function machineHardware(){const p=[];for(const x of [-.37,.37]){const g=new T.CylinderGeometry(.051,.051,.45,10);g.translate(x,-.11,.35);p.push(g);const collar=new T.CylinderGeometry(.065,.065,.08,10);collar.translate(x,.13,.35);p.push(collar);}for(const z of [-.38,.38])for(let k=0;k<9;k++){const g=new T.BoxGeometry(.07,.035,.021);g.translate(-.34+k*.085,.37,z);p.push(g);}for(const x of [-.38,.38]){const points=[new T.Vector3(x,-.35,-.35),new T.Vector3(x*.9,.17,-.35),new T.Vector3(x*.65,.25,.05),new T.Vector3(x*.3,.10,.18)];p.push(new T.TubeGeometry(new T.CatmullRomCurve3(points),12,.011,5));}return merged(p);}
function equipmentLadder(){const p=[];for(const x of [-.12,.12]){const g=new T.BoxGeometry(.012,1,.012);g.translate(x,0,0);p.push(g);}for(let k=0;k<19;k++){const g=new T.BoxGeometry(.25,.008,.018);g.translate(0,-.48+k*.053,0);p.push(g);}for(let k=0;k<6;k++){const g=new T.TorusGeometry(.14,.005,4,12,Math.PI).rotateY(Math.PI/2);g.translate(0,-.35+k*.14,.013);p.push(g);}return merged(p);}
function recoveryPipes(){const p=[];for(const x of [-.15,.15]){const pts=[[x,-.48,0],[x,-.16,0],[x,.30,0],[x,.38,.16],[0,.38,.22]].map(v=>new T.Vector3(...v));p.push(new T.TubeGeometry(new T.CatmullRomCurve3(pts),20,.045,8));}return merged(p);}
export function industrialShapes(){const s={hullPanels:hullPanels(),machineHardware:machineHardware(),equipmentLadder:equipmentLadder(),recoveryPipes:recoveryPipes(),yardFrame:yard(),yardFrameLow:yard(true),shipRibs:ribs(),shipRibsLow:ribs(true),shipRibsFar:ribs(true,true),pressMachine:press(),pressMachineFar:press(true),factoryRoof:roof(),factoryRoofLow:roof(true),shipHullFar:new T.SphereGeometry(.5,8,4),shipHull:new T.SphereGeometry(.5,28,14),shipHullLow:new T.SphereGeometry(.5,10,6)};for(const g of Object.values(s)){g.computeBoundingBox();g.computeBoundingSphere();}return s;}
