import {PROJECTS,DISTRICTS,PORTS,GATES,orbitalReport,offer} from './orbital.mjs';
import {xy} from './catalog.mjs';
const fmt=n=>Math.round(n).toLocaleString('en-US');
export function orbitalPanelHTML(s,a){
 const o=s.orbital,r=orbitalReport(s,a),next=offer(s);
 const projectCards=Object.entries(PROJECTS).map(([k,d])=>{
  const p=o.projects[k],locked=o.completed<d.orders||s.highPopulation<d.pop,status=!p.built?'尚未建造':!p.enabled?'保養待機':r.online[k]?'營運中':'供應或連線不足';
  const load=r.online[k]?`<span class="positive">● ${status}</span>`:`<span>${status}</span>`;
  return `<article class="megacard"><div class="mega-symbol">${{arch:'∩',lift:'↟',citadel:'◇'}[k]}</div><div><span class="eyebrow">${load}</span><h3>${d.name}</h3><p>${d.description}</p><div class="orbital-spec"><span>建造 <b>${fmt(d.cost)}</b></span><span>維護 <b>${d.upkeep} / 月</b></span><span>待機 <b>${d.upkeep*.15} / 月</b></span></div><p class="tiny">解鎖：完成 ${d.orders} 張訂單 · 歷史人口 ${fmt(d.pop)}<br>啟用負載：電力 ${d.power} · 水 ${d.water} · 熱 ${d.heat}，接至${DISTRICTS[d.anchor].name}預留船塢。</p><div class="modal-actions">${p.built?`<button data-orbit-action="toggle" data-key="${k}">${p.enabled?'轉為待機':'恢復營運'}</button>`:`<button class="primary" data-orbit-action="construct" data-key="${k}" ${locked||s.cash<d.cost?'disabled':''}>${locked?'尚未解鎖':'建造 '+fmt(d.cost)}</button>`}<button data-monument="${k}">查看場址</button>${k==='arch'&&p.built?'<button data-gate="0">親自穿越 →</button>':''}</div></div></article>`;
 }).join('');
 const orders=o.orders.map(c=>{const st=o.stock[c.deck],shipping=c.status==='shipping';return `<section class="order-row"><span class="eyebrow">${DISTRICTS[c.deck].name} · ${shipping?'運送中':'備料中'}</span><h3>${c.title}</h3><div class="orbital-spec"><span>合金 <b>${shipping?'已裝船':fmt(st.alloy)+' / '+c.alloy}</b></span><span>零件 <b>${shipping?'已裝船':fmt(st.parts)+' / '+c.parts}</b></span><span>酬勞 <b>${fmt(shipping?c.payment:Math.round(c.reward*(r.online.lift?1.25:1)))}</b></span></div><p class="tiny">${shipping?`預計 ${Math.max(0,c.eta-s.month)} 個月後到款，目的港需維持營運。`:'材料齊備且本區有運作船塢時會自動裝船。'} · 剩 ${Math.max(0,c.deadline-s.month)} 個月交貨</p>${!shipping?`<button data-orbit-action="cancel" data-key="${c.id}">取消 · 150</button>`:''}</section>`;}).join('');
 return `<p class="modal-intro">先讓居民就業，再把合金製成零件，交貨賺取巨構建設資金。兩區倉庫各自結算；開啟面板時時間暫停。</p><div class="orbit-summary"><div><small>已完成訂單</small><strong>${o.completed}</strong></div><div><small>累計出口入帳</small><strong>${fmt(o.earned)}</strong></div><div><small>軌道營運 / 月</small><strong class="${r.income-r.upkeep-r.productionCost>=0?'positive':'negative'}">${fmt(r.income-r.upkeep-r.productionCost)}</strong></div></div>
 <nav class="orbit-jumps"><a href="#district-stock">01 倉庫</a><a href="#order-book">02 訂單</a><a href="#mega-projects">03 巨構</a></nav>
 <div class="sector-grid" id="district-stock">${r.areas.map((d,n)=>`<section class="sector-card"><span class="eyebrow">${n?'FOLDED HARBOUR':'DAWN GARDENS'}</span><h3>${d.name}</h3><p>${fmt(d.pop)} 位居民 · ${d.docks} 座運作船塢</p><div class="status-row"><span>合金庫存</span><strong>${fmt(o.stock[n].alloy)} / ${d.capacity}</strong></div><div class="status-row"><span>零件庫存</span><strong>${fmt(o.stock[n].parts)} / ${d.capacity}</strong></div><p class="tiny">下月：合金生產 ${d.alloy}；加工消耗 ${d.parts*3} 合金 → ${d.parts} 零件。<br>市營材料支出 ${d.productionCost} / 月；工業就業 ${fmt(d.industry)}、精密製造就業 ${fmt(d.makers)}。倉庫滿載會停止對應生產。</p><button data-district="${n}">前往街區</button><button data-port="${n}">查看船塢</button></section>`).join('')}</div>
 <h3 id="order-book">出口訂單 · ${o.orders.length} / 2</h3>${orders||'<p class="notice">目前沒有承接訂單。庫存仍會生產，達到上限後停產。</p>'}
 <section class="offer-card"><span class="eyebrow">下一份邀約</span><h3>${next.title}</h3><p>合金 ${next.alloy} ＋ 零件 ${next.parts} → <strong>${fmt(Math.round(next.reward*(r.online.lift?1.25:1)))}</strong> 信用點</p><p class="tiny">24 個月交貨期限；逾期費 400。一次可承接兩份；酬勞於裝船時鎖定。未啟用升降港時運送兩個月。</p><div class="modal-actions">${r.areas.map((d,n)=>`<button data-orbit-action="accept" data-key="${n}" ${o.orders.length>=2||!d.docks?'disabled':''}>由${d.name}承接</button>`).join('')}</div></section>
 <div class="visitor-card"><span class="eyebrow">AURORA · 巨型訪客船</span><h3>${!o.visitorUnlocked?'迎接極光號':r.visitorPresent?'極光號正在停泊':'極光號正在巡航'}</h3><p>${!o.visitorUnlocked?`完成 2 張訂單並達到 600 人後自動來訪。目前 ${o.completed} / 2 張。`:`每 12 個月停泊 5 個月；${r.visitorPresent?'本次尚有 '+(5-o.visitorCycle)+' 個月':'再 '+(12-o.visitorCycle)+' 個月返回'}。本月服務 ${r.tourists} 位旅客，收入 ${r.tourists*5}。`}</p><p class="tiny">訪客船自動來訪，不收購船費。兩端船塢需要營運，訪客量受人口與滿意度限制。</p><button data-monument="visitor">前往觀景位置</button></div>
 <h3 id="mega-projects">巨構工程 · 預留空域</h3><p class="tiny">巨構使用固定場址，不會吞掉既有建築。水電與散熱不足會停止效果；維護費仍須支付，可手動待機至 15%。</p>${projectCards}
 <p class="notice">浮航城邦目前招待 ${r.researchers} 位外來研究員（獨立於主城居民），租金 ${r.researchers*9} / 月。巨構維護 ${r.upkeep} / 月；兩區市營材料支出 ${r.productionCost} / 月。這些都已列入財政面板，訂單交貨款則在交貨月份入帳。</p>`;
}
